### ISSUE TITLE
Better documentation/API

### ISSUE THREAD

**Issue by brucou** [tsers-js/core#10]
This is not an urgent issue, but I log it here to keep it in mind. 

I got around the TSERS API and idea relatively quick (and yet not that quick) because I usually wire my cycles by hand and I have a similar API (conceptually similar but the API is quite different), so it was not so hard to see the abstraction. However, it would really help to define explain TSERS not in function of cycle (which would assume it is destined to people who know cycle), but in function of functional reactive programming, and `your app as a circuit`. Rxjs operators are basic signal transformers, components are composite signal transformers made from basic signal transformers, and you add the feedback loop with a function (run, is it? but that would more be sth like `connect` or `wire`?), and you switch on the circuit with `execute` (I'd rather use a verb than a noun, that would be the real run in my understanding).

I approached this in my case as:
- specification
- runtime

In the specification part, you have three concepts:
- signals
- signal transformers
- feedback loop

from which you derive : 
- component (logic controller? integrated circuit? they are distinguished from the lower-level entities because they can feature feedback loop)
- application

through composition.

In the runtime part, you have:
- parametrization of initialization order
- orderly subscription of signals/component/application
- orderly disposal of signals/component/application

And the API should in my opinion relate to that conceptual map rather than looking for brevity.

**Comment by milankinen** [comment]
Yeah I agree. The current documentation has way too many references to Cycle and my intention is make a complete refactoring of docs. The model you proposed looks nice, although I'm not sure what you mean with "component" and "application". I'd just focusing on saying all UI functions as "applications" because there are already pretty much cognitive load with "signals", "transformers" and "execute". The biggest challenge is trying to keep the text as simple as possible so that less experienced developers could understand it too.

For API surface, some methods are gonna changes (#6). I'm planning to rename also `run` because it doesn't describe the actual behaviour and is just an unnecessary backreference to Cycle. Before the release, the name of `run` was actually `loop` which describes the behaviour IMO much better, but I decided to use `run` because I though it was easier for Cyclist to understand. Bad decision to say - and going to be fixed. 

I'm gonna create a branch for this and post references to commits so that that we can discuss the changes before merging them into master.

**Comment by brucou** [comment]
Great. Yes, the distinction between components and applications is to be refined, as they essentially have the same operational semantics (taking signals, outputing signals, and performing side-effects in the process). In my understanding this, taking the metaphor of a tree data structure, this is just like the root node, and the other nodes : they are all nodes, but only one node stands at the top. So you could imagine application as being the top level component or something like that; and instead of saying top-level component all the time, you say application. 

The difference between signal transformer and component in my mind are : 
- signal transformers do not perform side-effects and do not have feedback loop. Think about a regular rxjs operator. Signal transformers would then be pure functions (of signals).
- components MAY have feedback loop and MAY perform side-effects. In a way you can think about that as higher-powered signal transformers. They would be the possibly impure side-effectful functions. <del>As a matter of fact, I can't think how a pure component would be useful. If you take a signal and returns a signal and do nothing else, for me, it is just like the `map` operator</del>. 

I see the components as being built from input signals, signal transformers (for the pure processing), and drivers (for the side-effects). They would still separate the pure from the impure side but they would encapsulate their drivers making them 'private' or 'isolated'. It is intended to be a reusable unit, which comes tested out of the box by the component maker (white-box testing).

**Comment by milankinen** [comment]
New docs added in `1.0.0` release
- [Core concepts](https://github.com/tsers-js/core#core-concepts) in the `core` repository
- [Tutorial](https://github.com/tsers-js/examples#tutorial) in the `examples` repository

I'd happily hear some comments and improvement suggestions :smile:

**Comment by brucou** [comment]
I'll come back to that over the week-end
